{% set name = "herbie-data" %}
{% set version = "2023.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
       https://files.pythonhosted.org/packages/d7/57/887184fe2cf9fa9558aacdbefc511f510ff8e2d08b23479a8d93b95228e8/herbie-data-2023.3.0.tar.gz
       https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=671526&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=123
       https://pypi.io/packages/source/h/herbie-data/herbie-data-2022.3.0.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9415c79e72f48cb816513b987a860d1ff7733292bde4f7b31cdab0e577f1588c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
      - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm

  run:
    - cfgrib >=0.9.10.1
    - metpy
    - numpy
    - pandas
    - python >=3.8
    - pygrib
    - toml
    - xarray

test:
  commands:
    - pip check
  imports:
    - herbie
    - herbie.models
  requires:
    - pip

about:
  home: https://github.com/blaylockbk/Herbie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download numerical weather prediction GRIB2 model data.
  description: |
    Herbie is a python package that downloads recent and archived numerical weather
    prediction (NWP) model output from different cloud archive sources. Its most
    popular capability is to download HRRR model data. NWP data in GRIB2 format
    can be read with xarray+cfgrib. Much of this data is made available through the
    NOAA Open Data Dissemination (NODD) Program (formerly the Big Data Program)
    which has made weather data more accessible than ever before.
  doc_url: https://herbie.readthedocs.io/
  dev_url: https://github.com/blaylockbk/Herbie

extra:
  recipe-maintainers:
    - blaylockbk
